language: node_js

node_js:
  - "0.10"

notifications:
    email:
        - saitodisse@gmail.com

# script:
#   - npm test
#   - npm run-script cover
#   - cat ./coverage/lcov.info | node ./node_modules/coveralls/bin/coveralls